name: deploy
on:
  push:
    branches: [master]

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set lower case envs
        run: echo "REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]' | tr '/' '_')" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{github.actor}}/${{env.REPOSITORY}}:latest,ghcr.io/${{github.actor}}/${{env.REPOSITORY}}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
